name: build
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Library
        run: make -B

      - name: Generate Artifacts
        run: |
          mkdir -p release/lib
          cp -vr include release
          cp -v libflo.a release/lib/
          cp -v libflo.so release/lib/
          tar -czvf release.tar.gz release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release.tar.gz
          path: release.tar.gz
          if-no-files-found: error
          overwrite: true
