name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Library
        run: make -B

      - name: Generate Branch
        run: |
          mkdir -p release/lib
          cp -vr include release
          cp -v libflo.a release/lib/
          cp -v libflo.so release/lib/

      - name: Upload Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
